### ISSUE TITLE
上下文功能不可以

### ISSUE THREAD

**Issue by zenglincient** [razertory/gpt-wework#1]
似乎没有实现上下文的功能

**Comment by razertory** [comment]
上下文功能实现比较简单，这个很快。

**Comment by ghost** [comment]
请问orgId如何获取呀

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/32920883/225186039-ca3fd71c-77d3-49b4-907e-4956f1bbc060.png)
我这边报了这个错 可以帮忙看下嘛

**Comment by razertory** [comment]
> 似乎没有实现上下文的功能

https://github.com/razertory/gpt-wework/blob/main/service/wechat.go#L35 已经改动发布了。配置上下文大小可以控制能力

**Comment by razertory** [comment]
> ![image](https://user-images.githubusercontent.com/32920883/225186039-ca3fd71c-77d3-49b4-907e-4956f1bbc060.png) 我这边报了这个错 可以帮忙看下嘛

这个问题。在新的版本里面解决了，不再需要 orgId
