### ISSUE TITLE
只支持ChatGPT-3？

### ISSUE THREAD

**Issue by guohaocn** [razertory/gpt-wework#4]
只支持ChatGPT-3？支持3.5甚至4吗？

**Comment by razertory** [comment]
现在默认是 3.5 的。修改这一行可以自定义模型
https://github.com/razertory/gpt-wework/blob/main/service/gpt.go#L71

**Comment by lonny1987** [comment]
请问这个代码是全的吗？是可以正常配置运行的吧？
