### ISSUE TITLE
%!s(int=111)   CheckWeixinSign: panic(111)

### ISSUE THREAD

**Issue by chaovinci** [razertory/gpt-wework#7]
2023/04/24 05:19:28 [Recovery] 2023/04/24 - 05:19:28 panic recovered:
GET /wechat/check?msg_signature=a7a99c6ff92d0fff34bbdea46b4f8ea08ec3b900&timestamp=1682313568&nonce=1682136244&echostr=XnroEvJND8Fc5oPucdaAzUBnGe0q5mQeAP6t0aKTzsQPRDKMNpcAsNqdU6Jp25KZKctIN2a7DI%2BaENvXiH2GUg%3D%3D HTTP/1.1

%!s(int=111)
/gpt-wework/service/wechat.go:242 (0x798b75)
	CheckWeixinSign: panic(111)
仔细检查过 .env中的配置，核对无误

**Comment by chaovinci** [comment]
感觉是 .env的读取有问题，我将config Go中的读取代码去掉，直接把token写到文件，就运行正常了

**Comment by razertory** [comment]
> 感觉是 .env的读取有问题，我将config Go中的读取代码去掉，直接把token写到文件，就运行正常了

https://github.com/razertory/gpt-wework/pull/8
